import styles from "../styles/Classes.module.css";
import Head from "next/head";
import NavbarHome from "../components/NavbarHome";
import Category from "../models/Category";
import dbConnect from "../util/mongodb";

export const getStaticProps = async () => {
  dbConnect();
  let newCategoryData = await Category.find();
  newCategoryData = JSON.parse(JSON.stringify(newCategoryData));

  return {
    props: { classes: newCategoryData },
  };
};
const Home = ({ classes }) => {
  return (
    <div className={styles.masterContainer}>
      <div className={styles.explainContent}>
        <div className={styles.explainContainer}>
          <NavbarHome props={classes}></NavbarHome>
        </div>
      </div>
      <div className={styles.categoriesContainer}>
        <Head>
          <title>Aprendendo a Codar</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </div>
  );
};

export default Home;
