// Importando bibliotecas e estilizações do css.
import styles from "../styles/Classes.module.css";
import Head from "next/head";
import HeroComponent from "../components/Hero";
import Category from "../models/Category";
import Class from "../models/Class";
import dbConnect from "../util/mongodb";
import dbDisconnect from "../util/mongodb";


// Populando os caminhos para o nextjs. https://nextjs.org/docs/basic-features/data-fetching
export const getStaticProps = async () => {
  // Estabelecendo conexão com o banco de dados
  dbConnect();
  
  // Procurando Categorias
  let newCategoryData = null;
  let newClassesData = null;

  try {
    newCategoryData = await Category.find();
    newCategoryData = JSON.parse(JSON.stringify(newCategoryData));
  } catch (err) {
    console.log("ERROR on fetching all categories!!--> ", err);
  }

  // Procurando Aulas
  try {
    newClassesData = await Class.find();
    newClassesData = JSON.parse(JSON.stringify(newClassesData));
  } catch (err) {
    console.log("Error", err)
  }

  // Finalizando conexão com o banco de dados
  dbDisconnect();

  // Retornando dados que foram recolhidos do banco de dados e re-
  // passando para o componente principal
  return {
    props: { categorias: newCategoryData, classes: newClassesData  },
  };
};

//Componente principal da homepage
const Home = ({ categorias , classes}) => {
  return (
    <div className={styles.masterContainer}>
      <Head>
        <title>Aprendendo a Codar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroComponent categorias={categorias} classes={classes}></HeroComponent>
    </div>
  );
};

export default Home;
