// Importando bibliotecas e estilizações do css.
import styles from "../styles/Classes.module.css";
import Head from "next/head";
import HomeComponent from "../components/HomeComponent";
import Footer from "../components/Footer";
import Category from "../models/Category";
import dbConnect from "../util/mongodb";
import dbDisconnect from "../util/mongodb";

// Populando os caminhos para o nextjs. https://nextjs.org/docs/basic-features/data-fetching
export const getStaticProps = async () => {
  // Estabelecendo conexão com o banco de dados
  dbConnect();
  let newCategoryData = null;

  try {
    newCategoryData = await Category.find();
    newCategoryData = JSON.parse(JSON.stringify(newCategoryData));
  } catch (err) {
    console.log("ERROR on fetching all categories!!--> ", err);
  }

  // Finalizando conexão com o banco de dados
  dbDisconnect();

  // Retornando dados que foram recolhidos do banco de dados e re-
  // passando para o componente principal
  return {
    props: { classes: newCategoryData },
  };
};

//Componente principal da homepage
const Home = ({ classes }) => {
  return (
    <div className={styles.masterContainer}>
      <Head>
        <title>Aprendendo a Codar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.explainContent}>
        <div className={styles.explainContainer}>
          <HomeComponent props={classes}></HomeComponent>
        </div>
      </div>
      <div className={styles.categoriesContainer}></div>
      <Footer></Footer>
    </div>
  );
};

export default Home;
